# Generated by Django 3.1 on 2021-04-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('in stock', 'In stock'), ('out os stock', 'Out of stock')], default='default status', max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
